const curated=[
{id:'c1',company:'Shop Moda B',sector:'Tienda de ropa',district:'Callao',phone:'922008247',web:'https://shop-moda-b.ueniweb.com/',source:'https://shop-moda-b.ueniweb.com/',need:'Inventario / POS',score:88,status:'Nuevo',note:'Tienda con stock en almacén y ventas por encargo. Potencial para catálogo propio, control de stock y pedidos.'},
{id:'c2',company:'Menta Store by E&Y',sector:'Tienda de ropa',district:'Callao',phone:'967092026',web:'https://menta-store-by-e-y.ueniweb.com/',source:'https://menta-store-by-e-y.ueniweb.com/',need:'Inventario / POS',score:87,status:'Nuevo',note:'Negocio con stock y variedad de prendas. Buen candidato para inventario, catálogo y pedidos por WhatsApp.'},
{id:'c3',company:'Marconi',sector:'Moda / accesorios',district:'Callao',phone:'943969795',web:'https://marconi.ueniweb.com/',source:'https://marconi.ueniweb.com/',need:'Web / catálogo',score:82,status:'Nuevo',note:'Catálogo de ropa y accesorios. Oportunidad para una web propia más moderna, catálogo administrable y contacto directo.'},
{id:'c4',company:'Forever Young',sector:'Tienda de ropa',district:'Callao',phone:'997856401',web:'https://forever-young.ueniweb.com/',source:'https://forever-young.ueniweb.com/',need:'Inventario / POS',score:86,status:'Nuevo',note:'Negocio con stock y productos por temporadas. Potencial para control de inventario y catálogo de venta.'},
{id:'c5',company:"Diana's Style",sector:'Ropa y calzado',district:'Callao',phone:'955239912',web:'https://dianas-style.ueniweb.com/',source:'https://dianas-style.ueniweb.com/',need:'Inventario / POS',score:90,status:'Nuevo',note:'Maneja ropa de mujer, hombre, niños y calzado. Amplio catálogo: buen candidato para stock, catálogo y reportes.'},
{id:'c6',company:'Lumiere',sector:'Tienda de ropa',district:'Callao',phone:'947269872',web:'https://lumiere-1.ueniweb.com/',source:'https://lumiere-1.ueniweb.com/',need:'Web / catálogo',score:81,status:'Nuevo',note:'Tienda con productos y precios publicados. Oportunidad para una presencia digital propia y catálogo más comercial.'},
{id:'c7',company:'Fast Fashion',sector:'Tienda de ropa',district:'Callao',phone:'934007979',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:91,status:'Nuevo',note:'Teléfono y local público encontrados; sin web propia detectada en la fuente consultada. Oferta clara: web + catálogo + WhatsApp.'},
{id:'c8',company:'Dolieh',sector:'Tienda de ropa',district:'Callao',phone:'970577689',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:90,status:'Nuevo',note:'Negocio físico con teléfono público; sin web propia detectada en la fuente consultada. Alta prioridad para web y catálogo.'},
{id:'c9',company:'Blondy',sector:'Moda / confecciones',district:'Callao',phone:'916438283',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Inventario / POS',score:89,status:'Nuevo',note:'Confeccionista con ventas al por mayor y menor. Potencial para inventario, pedidos, catálogo y seguimiento comercial.'},
{id:'c10',company:'Mauva Fashion',sector:'Tienda de ropa',district:'Callao',phone:'951892559',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:88,status:'Nuevo',note:'Teléfono y dirección pública disponibles; sin web propia detectada en la fuente consultada. Buen candidato para presencia digital.'}
];
let leads=JSON.parse(localStorage.getItem('mjmLeadsV2GH')||'null')||curated;let editId=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('mjmLeadsV2GH',JSON.stringify(leads))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function opportunityText(l){return{'Web / catálogo':'Ofrecer una web rápida, catálogo administrable y contacto directo por WhatsApp.','Inventario / POS':'Ofrecer control de stock, ventas, movimientos, alertas y reportes.','Automatización / CRM':'Ofrecer seguimiento de clientes, recordatorios y automatización de tareas repetitivas.','Sistema a medida':'Proponer un diagnóstico corto y una herramienta adaptada al flujo real.'}[l.need]||'Detectar el cuello de botella y proponer una solución concreta.'}
function renderStats(){const hot=leads.filter(x=>x.score>=80&&!['Ganado','Perdido'].includes(x.status)).length;const contacted=leads.filter(x=>x.status!=='Nuevo').length;const won=leads.filter(x=>x.status==='Ganado').length;$('stats').innerHTML=`<div class="stat"><span>Total CRM</span><b>${leads.length}</b></div><div class="stat"><span>Prioridad alta</span><b>${hot}</b></div><div class="stat"><span>Contactados</span><b>${contacted}</b></div><div class="stat"><span>Ganados</span><b>${won}</b></div>`}
function renderFilters(){const d=$('district');const cur=d.value;const vals=[...new Set(leads.map(x=>x.district).filter(Boolean))].sort();d.innerHTML='<option value="all">Todos los distritos</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');d.value=vals.includes(cur)?cur:'all'}
function renderCRM(){renderFilters();renderStats();const q=$('q').value.toLowerCase(),d=$('district').value,n=$('need').value,s=$('status').value;const f=leads.filter(l=>(d==='all'||l.district===d)&&(n==='all'||l.need===n)&&(s==='all'||l.status===s)&&(`${l.company} ${l.sector} ${l.district} ${l.need} ${l.note}`.toLowerCase().includes(q))).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} de ${leads.length} leads`;$('grid').innerHTML=f.length?f.map(card).join(''):'<div class="empty">No hay leads con esos filtros.</div>'}
function card(l){const wa=l.phone?`<a class="btn green" target="_blank" rel="noopener" href="https://wa.me/51${l.phone.replace(/\D/g,'').replace(/^51/,'')}">WhatsApp</a>`:'';const web=l.web?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.web)}">Web</a>`:'';const source=l.source?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.source)}">Fuente</a>`:'';return `<article class="card"><div class="cardTop"><div><div class="name">${esc(l.company)}</div><div class="meta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="score ${l.score>=85?'hot':''}">${l.score}</div></div><div class="chips"><span class="chip">${esc(l.need)}</span><span class="chip ${l.status==='Nuevo'?'warn':'good'}">${esc(l.status)}</span>${!l.web?'<span class="chip bad">Sin web propia detectada</span>':''}${l.phone?'<span class="chip good">Con teléfono</span>':''}</div><div class="opportunity"><b>Qué venderle:</b> ${esc(opportunityText(l))}<br><span class="muted">${esc(l.note||'')}</span></div><div class="actions">${wa}${web}${source}<button class="btn" onclick="editLead('${l.id}')">Editar</button><button class="btn danger" onclick="removeLead('${l.id}')">Eliminar</button></div><div class="actions"><select class="ctl" onchange="setStatus('${l.id}',this.value)">${['Nuevo','Contactado','Interesado','Reunión','Ganado','Perdido'].map(x=>`<option ${x===l.status?'selected':''}>${x}</option>`).join('')}</select></div></article>`}
function openAdd(){editId=null;$('dialogTitle').textContent='Nuevo lead';['fCompany','fSector','fDistrict','fPhone','fWeb','fSource','fNote'].forEach(id=>$(id).value='');$('fNeed').value='Web / catálogo';$('fScore').value=80;$('fStatus').value='Nuevo';$('leadDialog').showModal()}
function editLead(id){const l=leads.find(x=>x.id===id);if(!l)return;editId=id;$('dialogTitle').textContent='Editar lead';$('fCompany').value=l.company;$('fSector').value=l.sector;$('fDistrict').value=l.district;$('fPhone').value=l.phone||'';$('fWeb').value=l.web||'';$('fSource').value=l.source||'';$('fNeed').value=l.need;$('fScore').value=l.score;$('fStatus').value=l.status;$('fNote').value=l.note||'';$('leadDialog').showModal()}
function saveLead(){const company=$('fCompany').value.trim();if(!company)return toast('Falta el nombre del negocio');const l={id:editId||crypto.randomUUID(),company,sector:$('fSector').value.trim()||'Negocio',district:$('fDistrict').value.trim()||'Lima',phone:$('fPhone').value.trim(),web:$('fWeb').value.trim(),source:$('fSource').value.trim(),need:$('fNeed').value,score:Math.max(1,Math.min(100,+$('fScore').value||80)),status:$('fStatus').value,note:$('fNote').value.trim()};if(editId)leads=leads.map(x=>x.id===editId?l:x);else leads.unshift(l);persist();$('leadDialog').close();renderCRM();toast('Lead guardado')}
function setStatus(id,status){const l=leads.find(x=>x.id===id);if(l){l.status=status;persist();renderCRM()}}
function removeLead(id){if(!confirm('¿Eliminar este lead?'))return;leads=leads.filter(x=>x.id!==id);persist();renderCRM()}
function showHot(){const f=leads.filter(x=>x.score>=80&&!['Ganado','Perdido'].includes(x.status)).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} oportunidades calientes`;$('grid').innerHTML=f.length?f.map(card).join(''):'<div class="empty">Aún no hay oportunidades calientes.</div>'}
function exportCSV(){const cols=['Empresa','Rubro','Distrito','Telefono','Web','Oportunidad','Score','Estado','Notas','Fuente'];const rows=leads.map(l=>[l.company,l.sector,l.district,l.phone,l.web,l.need,l.score,l.status,l.note,l.source]);const csv=[cols,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mjm-leads.csv';a.click();URL.revokeObjectURL(a.href)}
function restoreBase(){if(confirm('¿Restaurar la base curada? Esto reemplaza tus cambios locales.')){leads=curated.map(x=>({...x}));persist();renderCRM()}}
window.addEventListener('DOMContentLoaded',renderCRM);