const demo=[
{id:'d1',company:'Ferretería Demo',sector:'Ferretería',district:'San Miguel',phone:'',web:'',maps:'',need:'Web / catálogo',score:91,status:'Nuevo',note:'Sin web visible. Buen candidato para catálogo + WhatsApp.',source:'demo'},
{id:'d2',company:'Clínica Demo',sector:'Salud',district:'Pueblo Libre',phone:'',web:'',maps:'',need:'Automatización / CRM',score:86,status:'Nuevo',note:'Negocio con alta carga de citas y consultas.',source:'demo'}
];
let leads=JSON.parse(localStorage.getItem('mjmLeadsV2')||'null')||demo;
let searchResults=[];let editId=null;let googleReady=false;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('mjmLeadsV2',JSON.stringify(leads))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function needFor(p){const t=((p.primaryTypeDisplayName?.text||'')+' '+(p.primaryType||'')).toLowerCase();if(/store|shop|market|hardware|clothing|electronics|supermarket|retail|warehouse|car|parts|pharmacy/.test(t))return 'Inventario / POS';if(/doctor|dentist|clinic|beauty|spa|lawyer|accounting|real_estate|school|gym/.test(t))return 'Automatización / CRM';if(!p.websiteURI)return 'Web / catálogo';return 'Sistema a medida'}
function scorePlace(p){let s=50;if(!p.websiteURI)s+=22;else s+=4;if(p.nationalPhoneNumber)s+=8;if((p.userRatingCount||0)>=20)s+=7;if((p.userRatingCount||0)>=100)s+=5;if((p.rating||0)>=4)s+=4;const t=((p.primaryTypeDisplayName?.text||'')+'').toLowerCase();if(/store|ferreter|hardware|retail|distrib|import|clinic|dent|restaurant|beauty|gym/.test(t))s+=8;return Math.min(99,s)}
function placeToLead(p){const address=p.formattedAddress||'';const district=(address.split(',').slice(-3,-2)[0]||'Lima').trim();const need=needFor(p);const score=scorePlace(p);const signals=[];signals.push(p.websiteURI?'Tiene web pública':'Sin web pública detectada');if(p.nationalPhoneNumber)signals.push('Teléfono público disponible');if(p.userRatingCount)signals.push(`${p.userRatingCount} reseñas`);return{id:p.id||crypto.randomUUID(),company:p.displayName?.text||'Negocio',sector:p.primaryTypeDisplayName?.text||'Negocio',district,phone:p.nationalPhoneNumber||'',web:p.websiteURI||'',maps:p.googleMapsURI||'',need,score,status:'Nuevo',note:signals.join(' · '),source:'Google Places',rating:p.rating||0,reviews:p.userRatingCount||0}}
function opportunityText(l){return{'Web / catálogo':'Ofrecer web rápida, catálogo administrable, formulario y contacto directo por WhatsApp.','Inventario / POS':'Ofrecer control de stock, ventas, movimientos, alertas y reportes.','Automatización / CRM':'Ofrecer agenda, seguimiento de clientes, recordatorios y automatización de tareas repetitivas.','Sistema a medida':'Proponer un diagnóstico corto del proceso y una herramienta adaptada al flujo real.'}[l.need]||'Detectar el cuello de botella y proponer una solución concreta.'}
function renderStats(){const hot=leads.filter(x=>x.score>=80&&!['Ganado','Perdido'].includes(x.status)).length;const contacted=leads.filter(x=>x.status!=='Nuevo').length;const won=leads.filter(x=>x.status==='Ganado').length;const avg=leads.length?Math.round(leads.reduce((a,b)=>a+(+b.score||0),0)/leads.length):0;$('stats').innerHTML=`<div class="stat"><span>Total CRM</span><b>${leads.length}</b></div><div class="stat"><span>Prioridad alta</span><b>${hot}</b></div><div class="stat"><span>Contactados</span><b>${contacted}</b></div><div class="stat"><span>Ganados</span><b>${won}</b></div>`}
function renderFilters(){const d=$('district');const cur=d.value;const vals=[...new Set(leads.map(x=>x.district).filter(Boolean))].sort();d.innerHTML='<option value="all">Todos los distritos</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');d.value=vals.includes(cur)?cur:'all'}
function renderCRM(){renderFilters();renderStats();const q=$('q').value.toLowerCase(),d=$('district').value,n=$('need').value,s=$('status').value;const f=leads.filter(l=>(d==='all'||l.district===d)&&(n==='all'||l.need===n)&&(s==='all'||l.status===s)&&(`${l.company} ${l.sector} ${l.district} ${l.need} ${l.note}`.toLowerCase().includes(q))).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} de ${leads.length} leads`;$('grid').innerHTML=f.length?f.map(cardCRM).join(''):'<div class="empty">No hay leads con esos filtros.</div>'}
function cardCRM(l){const phone=l.phone?`<a class="btn green" target="_blank" rel="noopener" href="https://wa.me/${l.phone.replace(/\D/g,'')}">WhatsApp</a>`:'';const web=l.web?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.web)}">Web</a>`:'';const maps=l.maps?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.maps)}">Maps</a>`:'';return `<article class="card"><div class="cardTop"><div><div class="name">${esc(l.company)}</div><div class="meta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="score ${l.score>=85?'hot':''}">${l.score}</div></div><div class="chips"><span class="chip">${esc(l.need)}</span><span class="chip ${l.status==='Nuevo'?'warn':'good'}">${esc(l.status)}</span>${!l.web?'<span class="chip bad">Sin web</span>':''}${l.phone?'<span class="chip good">Con teléfono</span>':''}</div><div class="opportunity"><b>Oportunidad:</b> ${esc(opportunityText(l))}<br><span class="muted">${esc(l.note||'')}</span></div><div class="actions">${phone}${web}${maps}<button class="btn" onclick="editLead('${l.id}')">Editar</button><button class="btn danger" onclick="removeLead('${l.id}')">Eliminar</button></div><div class="actions"><select class="ctl" onchange="setStatus('${l.id}',this.value)">${['Nuevo','Contactado','Interesado','Reunión','Ganado','Perdido'].map(x=>`<option ${x===l.status?'selected':''}>${x}</option>`).join('')}</select></div></article>`}
function renderSearch(){const r=$('results');$('resultCount').textContent=searchResults.length?`${searchResults.length} encontrados`:'';r.innerHTML=searchResults.length?searchResults.map((l,i)=>`<article class="card"><div class="cardTop"><div><div class="name">${esc(l.company)}</div><div class="meta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="score ${l.score>=85?'hot':''}">${l.score}</div></div><div class="chips"><span class="chip">${esc(l.need)}</span>${!l.web?'<span class="chip bad">Sin web</span>':'<span class="chip">Con web</span>'}${l.phone?'<span class="chip good">Teléfono</span>':''}${l.reviews?`<span class="chip">${l.reviews} reseñas</span>`:''}</div><div class="opportunity"><b>Qué venderle:</b> ${esc(opportunityText(l))}<br><span class="muted">${esc(l.note)}</span></div><div class="actions"><button class="btn primary" onclick="addSearch(${i})">+ Añadir al CRM</button>${l.maps?`<a class="btn" target="_blank" href="${esc(l.maps)}">Maps</a>`:''}${l.web?`<a class="btn" target="_blank" href="${esc(l.web)}">Web</a>`:''}</div></article>`).join(''):'<div class="empty">Busca un rubro y una zona para generar prospectos reales.</div>'}
function setTab(tab){$('tabCrm').classList.toggle('on',tab==='crm');$('tabSearch').classList.toggle('on',tab==='search');$('crmPanel').classList.toggle('hidden',tab!=='crm');$('searchPanel').classList.toggle('hidden',tab!=='search');$('crmSection').classList.toggle('hidden',tab!=='crm');$('searchSection').classList.toggle('hidden',tab!=='search');if(tab==='crm')renderCRM();else renderSearch()}
function loadGoogle(){const key=localStorage.getItem('mjmGoogleKey')||'';$('apiKey').value=key;if(!key){$('searchStatus').textContent='Configura tu API key de Google Maps/Places para activar búsquedas reales.';return}if(window.google?.maps?.places){googleReady=true;$('searchStatus').textContent='Google Places conectado.';return}window.__mjmGoogleReady=()=>{googleReady=true;$('searchStatus').textContent='Google Places conectado.'};const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places&v=weekly&loading=async&callback=__mjmGoogleReady`;s.async=true;s.onerror=()=>{$('searchStatus').textContent='No se pudo cargar Google Places. Revisa la API key y sus restricciones.'};document.head.appendChild(s)}
function saveKey(){const key=$('apiKey').value.trim();if(!key)return toast('Ingresa una API key');localStorage.setItem('mjmGoogleKey',key);toast('Clave guardada');location.reload()}
async function searchPlaces(){if(!googleReady||!google?.maps?.places?.Place){$('searchStatus').textContent='Google Places aún no está conectado. Guarda una API key válida.';return}const term=$('searchTerm').value.trim(),zone=$('searchZone').value.trim()||'Lima, Perú';if(!term)return toast('Escribe un rubro o tipo de negocio');$('searchStatus').textContent='Buscando negocios públicos…';try{const{Place}=google.maps.places;const{places}=await Place.searchByText({textQuery:`${term} en ${zone}`,fields:['id','displayName','formattedAddress','nationalPhoneNumber','websiteURI','googleMapsURI','rating','userRatingCount','primaryType','primaryTypeDisplayName'],maxResultCount:20,language:'es',region:'PE'});searchResults=(places||[]).map(placeToLead).sort((a,b)=>b.score-a.score);$('searchStatus').textContent=`Listo: ${searchResults.length} negocios encontrados y puntuados automáticamente.`;renderSearch()}catch(e){console.error(e);$('searchStatus').textContent='La búsqueda falló. Verifica que Maps JavaScript API y Places API (New) estén habilitadas y que tu dominio esté permitido.'}}
function addSearch(i){const x=searchResults[i];if(!x)return;if(leads.some(l=>l.company===x.company&&l.district===x.district))return toast('Ese lead ya está en el CRM');leads.unshift({...x,id:crypto.randomUUID()});persist();renderStats();toast('Lead añadido al CRM')}
function openAdd(){editId=null;$('dialogTitle').textContent='Nuevo lead';['fCompany','fSector','fDistrict','fPhone','fWeb','fMaps','fNote'].forEach(id=>$(id).value='');$('fNeed').value='Web / catálogo';$('fScore').value=80;$('fStatus').value='Nuevo';$('leadDialog').showModal()}
function editLead(id){const l=leads.find(x=>x.id===id);if(!l)return;editId=id;$('dialogTitle').textContent='Editar lead';$('fCompany').value=l.company;$('fSector').value=l.sector;$('fDistrict').value=l.district;$('fPhone').value=l.phone||'';$('fWeb').value=l.web||'';$('fMaps').value=l.maps||'';$('fNeed').value=l.need;$('fScore').value=l.score;$('fStatus').value=l.status;$('fNote').value=l.note||'';$('leadDialog').showModal()}
function saveLead(){const company=$('fCompany').value.trim();if(!company)return toast('Falta el nombre del negocio');const l={id:editId||crypto.randomUUID(),company,sector:$('fSector').value.trim()||'Negocio',district:$('fDistrict').value.trim()||'Lima',phone:$('fPhone').value.trim(),web:$('fWeb').value.trim(),maps:$('fMaps').value.trim(),need:$('fNeed').value,score:Math.max(1,Math.min(100,+$('fScore').value||80)),status:$('fStatus').value,note:$('fNote').value.trim(),source:'manual'};if(editId)leads=leads.map(x=>x.id===editId?l:x);else leads.unshift(l);persist();$('leadDialog').close();renderCRM();toast('Lead guardado')}
function setStatus(id,status){const l=leads.find(x=>x.id===id);if(l){l.status=status;persist();renderCRM()}}
function removeLead(id){if(!confirm('¿Eliminar este lead?'))return;leads=leads.filter(x=>x.id!==id);persist();renderCRM()}
function showHot(){$('status').value='all';$('need').value='all';$('district').value='all';$('q').value='';setTab('crm');const f=leads.filter(x=>x.score>=80).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} oportunidades calientes`;$('grid').innerHTML=f.length?f.map(cardCRM).join(''):'<div class="empty">Aún no hay oportunidades calientes.</div>'}
function exportCSV(){const cols=['Empresa','Rubro','Distrito','Telefono','Web','Maps','Oportunidad','Score','Estado','Notas','Fuente'];const rows=leads.map(l=>[l.company,l.sector,l.district,l.phone,l.web,l.maps,l.need,l.score,l.status,l.note,l.source]);const csv=[cols,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mjm-leads.csv';a.click();URL.revokeObjectURL(a.href)}
function resetDemo(){if(confirm('¿Restaurar datos demo? Esto reemplaza tu CRM local.')){leads=[...demo];persist();renderCRM()}}
window.addEventListener('DOMContentLoaded',()=>{renderCRM();renderSearch();loadGoogle()});