const curated=[
{id:'c1',company:'Shop Moda B',sector:'Tienda de ropa',district:'Callao',phone:'922008247',web:'https://shop-moda-b.ueniweb.com/',source:'https://shop-moda-b.ueniweb.com/',need:'Inventario / POS',score:88,status:'Nuevo',note:'Tienda con stock y ventas por encargo. Potencial para catálogo propio, control de stock y pedidos.'},
{id:'c2',company:'Menta Store by E&Y',sector:'Tienda de ropa',district:'Callao',phone:'967092026',web:'https://menta-store-by-e-y.ueniweb.com/',source:'https://menta-store-by-e-y.ueniweb.com/',need:'Inventario / POS',score:87,status:'Nuevo',note:'Negocio con stock y variedad de prendas. Buen candidato para inventario, catálogo y pedidos por WhatsApp.'},
{id:'c3',company:'Marconi',sector:'Moda / accesorios',district:'Callao',phone:'943969795',web:'https://marconi.ueniweb.com/',source:'https://marconi.ueniweb.com/',need:'Web / catálogo',score:82,status:'Nuevo',note:'Catálogo de ropa y accesorios. Oportunidad para una web propia más moderna, catálogo administrable y contacto directo.'},
{id:'c4',company:'Forever Young',sector:'Tienda de ropa',district:'Callao',phone:'997856401',web:'https://forever-young.ueniweb.com/',source:'https://forever-young.ueniweb.com/',need:'Inventario / POS',score:86,status:'Nuevo',note:'Negocio con stock y productos por temporadas. Potencial para control de inventario y catálogo de venta.'},
{id:'c5',company:"Diana's Style",sector:'Ropa y calzado',district:'Callao',phone:'955239912',web:'https://dianas-style.ueniweb.com/',source:'https://dianas-style.ueniweb.com/',need:'Inventario / POS',score:90,status:'Nuevo',note:'Maneja ropa de mujer, hombre, niños y calzado. Amplio catálogo: buen candidato para stock, catálogo y reportes.'},
{id:'c6',company:'Lumiere',sector:'Tienda de ropa',district:'Callao',phone:'947269872',web:'https://lumiere-1.ueniweb.com/',source:'https://lumiere-1.ueniweb.com/',need:'Web / catálogo',score:81,status:'Nuevo',note:'Tienda con productos y precios publicados. Oportunidad para una presencia digital propia y catálogo más comercial.'},
{id:'c7',company:'Fast Fashion',sector:'Tienda de ropa',district:'Callao',phone:'934007979',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:91,status:'Nuevo',note:'Teléfono y local público encontrados; sin web propia detectada. Oferta clara: web + catálogo + WhatsApp.'},
{id:'c8',company:'Dolieh',sector:'Tienda de ropa',district:'Callao',phone:'970577689',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:90,status:'Nuevo',note:'Negocio físico con teléfono público; sin web propia detectada. Alta prioridad para web y catálogo.'},
{id:'c9',company:'Blondy',sector:'Moda / confecciones',district:'Callao',phone:'916438283',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Inventario / POS',score:89,status:'Nuevo',note:'Confeccionista con ventas al por mayor y menor. Potencial para inventario, pedidos, catálogo y seguimiento comercial.'},
{id:'c10',company:'Mauva Fashion',sector:'Tienda de ropa',district:'Callao',phone:'951892559',web:'',source:'https://www.cylex.com.pe/callao/tienda-de-ropa/',need:'Web / catálogo',score:88,status:'Nuevo',note:'Teléfono y dirección pública disponibles; sin web propia detectada. Buen candidato para presencia digital.'},
{id:'c11',company:'La Mafia Perú',sector:'Moda / streetwear',district:'Callao',phone:'977847616',web:'https://lamafiaperu.com/',source:'https://lamafiaperu.com/pages/quienes-somos',need:'Inventario / POS',score:91,status:'Nuevo',note:'WhatsApp publicado, tienda online y catálogo amplio. Potencial para control de stock, pedidos y automatización de operación.'},
{id:'c12',company:'ArtStore Perú',sector:'Insumos / retail',district:'Lince',phone:'997917624',web:'https://www.artstoreperu.com/',source:'https://www.artstoreperu.com/contactenos/',need:'Inventario / POS',score:90,status:'Nuevo',note:'Dos tiendas físicas y pedidos por WhatsApp. Buen candidato para inventario centralizado, pedidos y reportes.'},
{id:'c13',company:'Proditec Perú',sector:'Ferretería / servicios',district:'Cercado de Lima',phone:'963097344',web:'https://proditecperu.com/',source:'https://proditecperu.com/contacto/',need:'Inventario / POS',score:92,status:'Nuevo',note:'Ferretería con atención a empresas y WhatsApp de ventas. Potencial para catálogo B2B, stock y cotizaciones.'},
{id:'c14',company:'Bi Natural Perú',sector:'Retail / productos naturales',district:'Lima',phone:'940085756',web:'https://www.binaturalperu.com/',source:'https://www.binaturalperu.com/contactanos',need:'Automatización / CRM',score:87,status:'Nuevo',note:'Toma pedidos por WhatsApp y realiza delivery en Lima/Callao. Potencial para pedidos, seguimiento y CRM ligero.'},
{id:'c15',company:'Importadora Leisac',sector:'Importadora / suministros',district:'Callao',phone:'983516659',web:'https://importadoraleisac.com/',source:'https://importadoraleisac.com/contacto/',need:'Sistema a medida',score:94,status:'Nuevo',note:'Importadora con varios teléfonos comerciales y WhatsApp. Potencial para cotizaciones, stock, pedidos y trazabilidad comercial.'},
{id:'c16',company:'Label Perú SAC',sector:'Manufactura / etiquetas',district:'Callao',phone:'998224783',web:'https://labelperusac.com/',source:'https://labelperusac.com/contacto-de-negocios/',need:'Automatización / CRM',score:88,status:'Nuevo',note:'WhatsApp comercial y atención B2B. Potencial para CRM de cotizaciones, seguimiento de clientes y pedidos.'},
{id:'c17',company:'JMH Perú EIRL',sector:'Mantenimiento industrial',district:'Callao',phone:'936572120',web:'https://jmhperueirl.com/',source:'https://jmhperueirl.com/contacto/',need:'Automatización / CRM',score:87,status:'Nuevo',note:'Servicios industriales con WhatsApp comercial. Buen candidato para seguimiento de cotizaciones, clientes y órdenes de servicio.'},
{id:'c18',company:'Metálicas Unión',sector:'Industrial / metalmecánica',district:'Callao',phone:'998158416',web:'https://www.union.com.pe/',source:'https://www.union.com.pe/contactanos',need:'Sistema a medida',score:90,status:'Nuevo',note:'Operación industrial con visitas técnicas y ventas por WhatsApp. Potencial para cotizaciones, seguimiento y control de proyectos.'},
{id:'c19',company:'Termoclima Andina SAC',sector:'Climatización / ferretería',district:'Carmen de la Legua',phone:'940374020',web:'https://termoclimasac.com/',source:'https://termoclimasac.com/contact/',need:'Inventario / POS',score:91,status:'Nuevo',note:'Venta de artículos y atención por WhatsApp. Potencial para catálogo, inventario y cotizaciones.'},
{id:'c20',company:'Senvilab',sector:'Laboratorio / suministros',district:'Callao',phone:'963185087',web:'https://senvilab.com/',source:'https://senvilab.com/contactenos',need:'Inventario / POS',score:93,status:'Nuevo',note:'Pedidos por WhatsApp y productos especializados. Potencial para catálogo, stock, pedidos y trazabilidad.'},
{id:'c21',company:'Pulicorp',sector:'Servicios / limpieza industrial',district:'Callao',phone:'967516784',web:'https://pulicorp.com/',source:'https://pulicorp.com/contacto/',need:'Automatización / CRM',score:86,status:'Nuevo',note:'Cotizaciones y asesoría por WhatsApp. Potencial para CRM, seguimiento comercial y automatización de cotizaciones.'},
{id:'c22',company:'LS Group Perú',sector:'Distribución / industrial',district:'Carmen de la Legua',phone:'968769401',web:'https://www.lsgroup-p.com/',source:'https://www.lsgroup-p.com/contactanos/',need:'Inventario / POS',score:92,status:'Nuevo',note:'Cuenta con almacén en Callao y WhatsApp comercial. Buen candidato para stock, pedidos, cotizaciones y reportes.'},
{id:'c23',company:'Sortel Perú - Ventanilla',sector:'Tecnología / electrónica',district:'Ventanilla',phone:'947545109',web:'https://www.sortelperu.com/',source:'https://www.sortelperu.com/contactenos',need:'Inventario / POS',score:90,status:'Nuevo',note:'Tienda en Ventanilla con WhatsApp y productos tecnológicos. Potencial para stock, ventas, catálogo y servicio técnico.'},
{id:'c24',company:'Veterinaria Socialvet',sector:'Veterinaria',district:'Surquillo',phone:'991328751',web:'https://veterinariasocialvet.com/',source:'https://veterinariasocialvet.com/contacto/',need:'Automatización / CRM',score:91,status:'Nuevo',note:'Atención por WhatsApp y más de una sede. Potencial para agenda, recordatorios, historial de clientes y seguimiento.'},
{id:'c25',company:'INCTEC SAC',sector:'Tecnología / captura automática',district:'Callao',phone:'981396297',web:'https://inctec.pe/',source:'https://inctec.pe/contacto/',need:'Inventario / POS',score:89,status:'Nuevo',note:'Venta y soporte de equipos POS, código de barras y captura automática. Potencial para CRM comercial y gestión de inventario.'},
{id:'c26',company:'Onplus EIRL',sector:'Ferretería / tecnología',district:'Cercado de Lima',phone:'933825993',web:'https://onplusperu.com/',source:'https://onplusperu.com/contactenos/',need:'Inventario / POS',score:91,status:'Nuevo',note:'Tienda en Plaza Ferretero con WhatsApp de cotización. Potencial para inventario, catálogo y cotizaciones rápidas.'},
{id:'c27',company:'Patines Perú',sector:'Retail deportivo',district:'Lima',phone:'902743123',web:'https://www.patinesperu.com/',source:'https://www.patinesperu.com/contacto',need:'Inventario / POS',score:89,status:'Nuevo',note:'WhatsApp oficial para pagos y consultas de stock. Potencial para inventario, pedidos y automatización postventa.'},
{id:'c28',company:'Casablanca Home',sector:'Hogar / retail',district:'Santiago de Surco',phone:'970446434',web:'https://www.casablancahome.net/',source:'https://www.casablancahome.net/contacto',need:'Inventario / POS',score:90,status:'Nuevo',note:'Múltiples puntos de venta y pedidos por WhatsApp. Potencial para inventario centralizado, catálogo y pedidos.'},
{id:'c29',company:'Bellas Tienda',sector:'Belleza / salud',district:'Lima',phone:'977649176',web:'https://bella.tienda/',source:'https://bella.tienda/contacto/',need:'Automatización / CRM',score:85,status:'Nuevo',note:'WhatsApp oficial y venta de productos de belleza y salud. Potencial para seguimiento de clientes y automatización de pedidos.'}
];
const saved=JSON.parse(localStorage.getItem('mjmLeadsV2GH')||'null');
let leads=saved?(()=>{const map=new Map(saved.map(x=>[(x.company+'|'+x.phone).toLowerCase(),x]));return curated.map(c=>{const old=map.get((c.company+'|'+c.phone).toLowerCase());return old?{...c,...old,id:c.id}:c}).concat(saved.filter(s=>!curated.some(c=>(c.company+'|'+c.phone).toLowerCase()===(s.company+'|'+s.phone).toLowerCase())));})():curated.map(x=>({...x}));
let editId=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('mjmLeadsV2GH',JSON.stringify(leads))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function opportunityText(l){return{'Web / catálogo':'Ofrecer una web rápida, catálogo administrable y contacto directo por WhatsApp.','Inventario / POS':'Ofrecer control de stock, ventas, movimientos, alertas y reportes.','Automatización / CRM':'Ofrecer seguimiento de clientes, recordatorios y automatización de tareas repetitivas.','Sistema a medida':'Proponer un diagnóstico corto y una herramienta adaptada al flujo real.'}[l.need]||'Detectar el cuello de botella y proponer una solución concreta.'}
function renderStats(){const hot=leads.filter(x=>x.score>=80&&!['Ganado','Perdido'].includes(x.status)).length;const contacted=leads.filter(x=>x.status!=='Nuevo').length;const won=leads.filter(x=>x.status==='Ganado').length;$('stats').innerHTML=`<div class="stat"><span>Total CRM</span><b>${leads.length}</b></div><div class="stat"><span>Prioridad alta</span><b>${hot}</b></div><div class="stat"><span>Contactados</span><b>${contacted}</b></div><div class="stat"><span>Ganados</span><b>${won}</b></div>`}
function renderFilters(){const d=$('district');const cur=d.value;const vals=[...new Set(leads.map(x=>x.district).filter(Boolean))].sort();d.innerHTML='<option value="all">Todos los distritos</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');d.value=vals.includes(cur)?cur:'all'}
function renderCRM(){renderFilters();renderStats();const q=$('q').value.toLowerCase(),d=$('district').value,n=$('need').value,s=$('status').value;const f=leads.filter(l=>(d==='all'||l.district===d)&&(n==='all'||l.need===n)&&(s==='all'||l.status===s)&&(`${l.company} ${l.sector} ${l.district} ${l.need} ${l.note}`.toLowerCase().includes(q))).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} de ${leads.length} leads`;$('grid').innerHTML=f.length?f.map(card).join(''):'<div class="empty">No hay leads con esos filtros.</div>'}
function card(l){const wa=l.phone?`<a class="btn green" target="_blank" rel="noopener" href="https://wa.me/51${l.phone.replace(/\D/g,'').replace(/^51/,'')}">WhatsApp</a>`:'';const web=l.web?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.web)}">Web</a>`:'';const source=l.source?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.source)}">Fuente</a>`:'';return `<article class="card"><div class="cardTop"><div><div class="name">${esc(l.company)}</div><div class="meta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="score ${l.score>=85?'hot':''}">${l.score}</div></div><div class="chips"><span class="chip">${esc(l.need)}</span><span class="chip ${l.status==='Nuevo'?'warn':'good'}">${esc(l.status)}</span>${!l.web?'<span class="chip bad">Sin web propia detectada</span>':''}${l.phone?'<span class="chip good">WhatsApp</span>':''}</div><div class="opportunity"><b>Qué venderle:</b> ${esc(opportunityText(l))}<br><span class="muted">${esc(l.note||'')}</span></div><div class="actions">${wa}${web}${source}<button class="btn" onclick="editLead('${l.id}')">Editar</button><button class="btn danger" onclick="removeLead('${l.id}')">Eliminar</button></div><div class="actions"><select class="ctl" onchange="setStatus('${l.id}',this.value)">${['Nuevo','Contactado','Interesado','Reunión','Ganado','Perdido'].map(x=>`<option ${x===l.status?'selected':''}>${x}</option>`).join('')}</select></div></article>`}
function openAdd(){editId=null;$('dialogTitle').textContent='Nuevo lead';['fCompany','fSector','fDistrict','fPhone','fWeb','fSource','fNote'].forEach(id=>$(id).value='');$('fNeed').value='Web / catálogo';$('fScore').value=80;$('fStatus').value='Nuevo';$('leadDialog').showModal()}
function editLead(id){const l=leads.find(x=>x.id===id);if(!l)return;editId=id;$('dialogTitle').textContent='Editar lead';$('fCompany').value=l.company;$('fSector').value=l.sector;$('fDistrict').value=l.district;$('fPhone').value=l.phone||'';$('fWeb').value=l.web||'';$('fSource').value=l.source||'';$('fNeed').value=l.need;$('fScore').value=l.score;$('fStatus').value=l.status;$('fNote').value=l.note||'';$('leadDialog').showModal()}
function saveLead(){const company=$('fCompany').value.trim();if(!company)return toast('Falta el nombre del negocio');const l={id:editId||crypto.randomUUID(),company,sector:$('fSector').value.trim()||'Negocio',district:$('fDistrict').value.trim()||'Lima',phone:$('fPhone').value.trim(),web:$('fWeb').value.trim(),source:$('fSource').value.trim(),need:$('fNeed').value,score:Math.max(1,Math.min(100,+$('fScore').value||80)),status:$('fStatus').value,note:$('fNote').value.trim()};if(editId)leads=leads.map(x=>x.id===editId?l:x);else leads.unshift(l);persist();$('leadDialog').close();renderCRM();toast('Lead guardado')}
function setStatus(id,status){const l=leads.find(x=>x.id===id);if(l){l.status=status;persist();renderCRM()}}
function removeLead(id){if(!confirm('¿Eliminar este lead?'))return;leads=leads.filter(x=>x.id!==id);persist();renderCRM()}
function showHot(){const f=leads.filter(x=>x.score>=80&&!['Ganado','Perdido'].includes(x.status)).sort((a,b)=>b.score-a.score);$('count').textContent=`${f.length} oportunidades calientes`;$('grid').innerHTML=f.length?f.map(card).join(''):'<div class="empty">Aún no hay oportunidades calientes.</div>'}
function exportCSV(){const cols=['Empresa','Rubro','Distrito','WhatsApp','Web','Oportunidad','Score','Estado','Notas','Fuente'];const rows=leads.map(l=>[l.company,l.sector,l.district,l.phone,l.web,l.need,l.score,l.status,l.note,l.source]);const csv=[cols,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mjm-leads.csv';a.click();URL.revokeObjectURL(a.href)}
function restoreBase(){if(confirm('¿Restaurar la base curada? Esto reemplaza tus cambios locales.')){leads=curated.map(x=>({...x}));persist();renderCRM()}}
window.addEventListener('DOMContentLoaded',()=>{persist();renderCRM()});