(function(){
const SKEY='mjmInventoryCloneStateV1';
const q=id=>document.getElementById(id);const money=n=>'S/ '+Math.round(Number(n||0)).toLocaleString('es-PE');
let state={};try{state=JSON.parse(localStorage.getItem(SKEY)||'{}')}catch{state={}};
function save(){localStorage.setItem(SKEY,JSON.stringify(state))}
function st(l){return state[l.id]||{outcome:'Sin contactar',stage:'Interesado',next:'',quote:0,prob:50,note:'',accepted:false}}
function patch(id,p){state[id]={...st({id}),...p};save();renderAll()}
function stats(){const all=leads.length, sent=leads.filter(l=>st(l).outcome!=='Sin contactar').length, replies=leads.filter(l=>['Respondió','Interesado','Aceptó propuesta','Seguimiento'].includes(st(l).outcome)).length, wins=leads.filter(l=>st(l).stage==='Cerrado').length;q('stats').innerHTML=`<div class="stat"><span>Total prospectos</span><b>${all}</b></div><div class="stat"><span>Contactados</span><b>${sent}</b></div><div class="stat"><span>Respondieron</span><b>${replies}</b></div><div class="stat"><span>Cerrados</span><b>${wins}</b></div>`}
function filters(){const sectors=[...new Set(leads.map(l=>l.sector).filter(Boolean))].sort(),zones=[...new Set(leads.map(l=>l.district).filter(Boolean))].sort();const curS=q('sector').value,curZ=q('zone').value;q('sector').innerHTML='<option value="all">Todos los rubros</option>'+sectors.map(x=>`<option>${esc(x)}</option>`).join('');q('zone').innerHTML='<option value="all">Todas las zonas</option>'+zones.map(x=>`<option>${esc(x)}</option>`).join('');q('sector').value=sectors.includes(curS)?curS:'all';q('zone').value=zones.includes(curZ)?curZ:'all'}
function leadCard(l){const s=st(l),o=getOffer(l);return `<article class="leadCard"><div class="cardTop"><div><div class="leadName">${esc(l.company)}</div><div class="leadMeta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="priority">${l.score}</div></div><div class="badgeRow"><span class="badge blue">${esc(l.need)}</span><span class="badge ${s.outcome==='Sin contactar'?'amber':'green'}">${esc(s.outcome)}</span>${l.phone?'<span class="badge green">WhatsApp</span>':''}</div><div class="offerBox"><b>Qué ofrecerle</b>${esc(o.main)}</div><div class="cardActions"><button class="btn primary wide" onclick="openDetail('${l.id}')">Abrir prospecto</button>${l.phone?`<a class="btn whatsapp" target="_blank" rel="noopener" href="https://wa.me/51${String(l.phone).replace(/\D/g,'').replace(/^51/,'')}">WhatsApp</a>`:''}${l.web?`<a class="btn" target="_blank" rel="noopener" href="${esc(l.web)}">Web</a>`:''}</div></article>`}
function renderProspects(){filters();stats();const txt=q('q').value.toLowerCase(),sec=q('sector').value,zone=q('zone').value,out=q('out').value,sort=q('sort').value;let a=leads.filter(l=>(sec==='all'||l.sector===sec)&&(zone==='all'||l.district===zone)&&(out==='all'||st(l).outcome===out)&&(`${l.company} ${l.sector} ${l.district} ${l.need} ${l.note}`.toLowerCase().includes(txt)));a.sort(sort==='name'?(a,b)=>a.company.localeCompare(b.company):(a,b)=>b.score-a.score);q('count').textContent=`${a.length} de ${leads.length}`;q('grid').innerHTML=a.map(leadCard).join('')||'<div class="empty">Sin resultados.</div>'}
window.openDetail=function(id){const l=leads.find(x=>x.id===id);if(!l)return;const s=st(l),o=getOffer(l);q('modal').innerHTML=`<div class="sheetTop"><div><h2>${esc(l.company)}</h2><div class="leadMeta">${esc(l.sector)} · ${esc(l.district)} · Score ${l.score}</div></div><button class="close" onclick="detail.close()">×</button></div><div class="detailBlock"><h3>Oportunidad detectada</h3><p><b>${esc(o.main)}</b><br>${esc(o.hook)}</p></div><div class="detailBlock"><h3>Venta adicional</h3><p>${esc(o.extra)}</p></div><div class="detailBlock"><h3>Estado comercial</h3><div class="followForm"><select class="ctl" onchange="patchLead('${l.id}',{outcome:this.value})">${['Sin contactar','Mensaje enviado','Respondió','Interesado','Aceptó propuesta','Seguimiento','No interesado'].map(x=>`<option ${x===s.outcome?'selected':''}>${x}</option>`).join('')}</select><textarea class="ctl" rows="3" placeholder="Notas comerciales" onchange="patchLead('${l.id}',{note:this.value})">${esc(s.note||'')}</textarea></div></div><div class="detailBlock"><h3>Asistencia comercial</h3><div class="coachGrid"><button class="coachBtn" onclick="coach('${l.id}','respondio')">Respondió y quiere información</button><button class="coachBtn" onclick="coach('${l.id}','precio')">Preguntó por precio</button><button class="coachBtn" onclick="coach('${l.id}','duda')">Tiene dudas / no está seguro</button><button class="coachBtn" onclick="coach('${l.id}','reunion')">Quiere reunión o demo</button></div><div id="coachAnswer" class="coachAnswer">Elige una situación y te digo el objetivo y qué responder.</div></div><div class="cardActions">${l.phone?`<a class="btn whatsapp" target="_blank" href="https://wa.me/51${String(l.phone).replace(/\D/g,'').replace(/^51/,'')}">Abrir WhatsApp</a>`:''}<button class="btn primary" onclick="acceptLead('${l.id}')">Pasar a seguimiento</button></div>`;detail.showModal()}
window.patchLead=(id,p)=>patch(id,p);
window.coach=function(id,type){const l=leads.find(x=>x.id===id),o=getOffer(l);const m={respondio:`Objetivo: entender su proceso actual. Responde corto, menciona ${o.main.toLowerCase()} y haz una pregunta sobre cómo controlan hoy ese proceso.`,precio:'Objetivo: no competir solo por precio. Primero confirma alcance, volumen y problema actual; luego ofrece una propuesta concreta y escalable.',duda:`Objetivo: bajar el riesgo. Explica que puedes empezar con una solución simple enfocada en ${o.hook.toLowerCase()} y crecer después.`,reunion:'Objetivo: agendar. Propón una llamada/demo breve de 15–20 minutos y llega con 2 preguntas sobre su proceso y una propuesta visual.'};q('coachAnswer').textContent=m[type]||''}
window.acceptLead=function(id){patch(id,{accepted:true,outcome:'Aceptó propuesta',stage:'Interesado'});detail.close();setModule('accepted')}
function accepted(){return leads.filter(l=>st(l).accepted)}
function renderFollow(){const a=accepted();q('acceptedCount').textContent=a.length;const filt=q('followFilter').value,stage=q('followStageFilter').value,sort=q('followSort').value;const now=new Date();let arr=a.filter(l=>stage==='all'||st(l).stage===stage);arr=arr.filter(l=>{const s=st(l);if(filt==='all')return true;if(filt==='nodate')return !s.next;if(filt==='hot')return Number(s.prob)>=70;if(!s.next)return false;const d=new Date(s.next+'T12:00:00'),diff=Math.floor((d-now)/86400000);if(filt==='overdue')return diff<0;if(filt==='today')return diff===0;if(filt==='next7')return diff>=0&&diff<=7;return true});arr.sort((a,b)=>{const A=st(a),B=st(b);if(sort==='probability')return B.prob-A.prob;if(sort==='quote')return B.quote-A.quote;if(sort==='name')return a.company.localeCompare(b.company);return String(A.next||'9999').localeCompare(String(B.next||'9999'))});q('followStats').innerHTML=`<div class="stat"><span>En seguimiento</span><b>${a.length}</b></div><div class="stat"><span>Alta probabilidad</span><b>${a.filter(l=>st(l).prob>=70).length}</b></div><div class="stat"><span>Cotizado</span><b>${a.filter(l=>st(l).quote>0).length}</b></div><div class="stat"><span>Cerrados</span><b>${a.filter(l=>st(l).stage==='Cerrado').length}</b></div>`;q('acceptedGrid').innerHTML=arr.map(l=>{const s=st(l);return `<article class="acceptedCard"><div class="cardTop"><div><div class="leadName">${esc(l.company)}</div><div class="leadMeta">${esc(l.sector)} · ${esc(l.district)}</div></div><div class="amount">${s.quote?money(s.quote):'—'}</div></div><div class="badgeRow"><span class="badge blue">${esc(s.stage)}</span><span class="badge green">${s.prob}% prob.</span></div><div class="next">Próxima acción: ${s.next||'Sin fecha'}<br>${esc(s.note||'Sin notas')}</div><div class="cardActions"><button class="btn primary wide" onclick="editFollow('${l.id}')">Gestionar oportunidad</button></div></article>`}).join('')||'<div class="empty">Aún no hay oportunidades en seguimiento.</div>'}
window.editFollow=function(id){const l=leads.find(x=>x.id===id),s=st(l);q('modal').innerHTML=`<div class="sheetTop"><div><h2>${esc(l.company)}</h2><div class="leadMeta">Seguimiento comercial</div></div><button class="close" onclick="detail.close()">×</button></div><div class="detailBlock"><div class="followForm"><label>Etapa<select class="ctl" onchange="patchLead('${id}',{stage:this.value})">${['Interesado','Por cotizar','Cotización enviada','Negociando','Fecha confirmada','Servicio realizado','Cobro pendiente','Cerrado'].map(x=>`<option ${x===s.stage?'selected':''}>${x}</option>`).join('')}</select></label><label>Próxima acción<input class="ctl" type="date" value="${s.next||''}" onchange="patchLead('${id}',{next:this.value})"></label><label>Monto cotizado<input class="ctl" type="number" value="${s.quote||0}" onchange="patchLead('${id}',{quote:+this.value})"></label><label>Probabilidad %<input class="ctl" type="number" min="0" max="100" value="${s.prob||50}" onchange="patchLead('${id}',{prob:+this.value})"></label><label>Notas<textarea class="ctl" rows="4" onchange="patchLead('${id}',{note:this.value})">${esc(s.note||'')}</textarea></label></div></div><div class="cardActions"><button class="btn" onclick="document.getElementById('quoteLead').value='${id}';detail.close();setModule('quote');calcQuote()">Cotizar</button>${l.phone?`<a class="btn whatsapp" target="_blank" href="https://wa.me/51${String(l.phone).replace(/\D/g,'').replace(/^51/,'')}">WhatsApp</a>`:''}</div>`;detail.showModal()}
function setModule(name){document.querySelectorAll('.module').forEach(x=>x.classList.add('hidden'));q(name+'Module').classList.remove('hidden');document.querySelectorAll('.moduleBtn').forEach(b=>b.classList.toggle('on',b.dataset.module===name));if(name==='accepted')renderFollow();if(name==='quote')fillQuoteLeads()}
window.setModule=setModule;
function fillQuoteLeads(){const cur=q('quoteLead').value;q('quoteLead').innerHTML='<option value="">Cotización libre</option>'+leads.map(l=>`<option value="${l.id}">${esc(l.company)}</option>`).join('');q('quoteLead').value=[...q('quoteLead').options].some(o=>o.value===cur)?cur:''}
window.calcQuote=function(){const type=+q('quoteType').value,scope=+q('quoteScope').value,complex=+q('quoteComplex').value,hours=+q('quoteHours').value,base=+q('quoteBase').value,margin=+q('quoteMargin').value/100,discount=+q('quoteDiscount').value/100;let price=(base+(hours*35))*type*scope*complex;if(q('quoteIntegration').checked)price+=180;if(q('quoteData').checked)price+=120;if(q('quoteTraining').checked)price+=90;const pre=price*(1+margin),final=pre*(1-discount),low=final*.9,high=final*1.15;q('quoteResult').innerHTML=`<span class="miniLabel">Precio recomendado</span><div class="quotePrice">${money(final)}</div><div class="quoteRange">Rango sugerido: ${money(low)} – ${money(high)}</div><div class="quoteHealth">Propuesta inicial editable. Valida alcance antes de cerrar.</div><div class="quoteBreakdown"><div class="quoteLine"><span>Base + horas</span><b>${money(base+hours*35)}</b></div><div class="quoteLine"><span>Complejidad / alcance</span><b>x ${(type*scope*complex).toFixed(2)}</b></div><div class="quoteLine"><span>Margen</span><b>${Math.round(margin*100)}%</b></div><div class="quoteLine"><span>Descuento</span><b>${Math.round(discount*100)}%</b></div></div><div class="quoteActions"><button class="btn whatsapp wide" onclick="copyQuote(${Math.round(final)})">Copiar propuesta breve</button><button class="btn primary wide" onclick="saveQuote(${Math.round(final)})">Guardar en seguimiento</button></div>`}
window.copyQuote=async function(n){const id=q('quoteLead').value,l=leads.find(x=>x.id===id);const text=`Hola${l?' '+l.company:''}, te comparto una propuesta referencial para la solución conversada: ${money(n)}. Incluye implementación inicial y configuración según alcance. Podemos ajustar el precio final luego de validar el proceso y requerimientos.`;try{await navigator.clipboard.writeText(text);toast('Propuesta copiada')}catch{alert(text)}}
window.saveQuote=function(n){const id=q('quoteLead').value;if(!id)return toast('Selecciona un prospecto');patch(id,{accepted:true,quote:n,stage:'Cotización enviada',outcome:'Seguimiento'});toast('Cotización guardada');setModule('accepted')}
function renderAll(){renderProspects();renderFollow()}
window.renderAll=renderAll;
function init(){document.querySelectorAll('.moduleBtn').forEach(b=>b.onclick=()=>setModule(b.dataset.module));['q','sector','zone','out','sort'].forEach(id=>q(id).addEventListener(id==='q'?'input':'change',renderProspects));['followFilter','followStageFilter','followSort'].forEach(id=>q(id).addEventListener('change',renderFollow));['quoteType','quoteScope','quoteComplex','quoteHours','quoteBase','quoteMargin','quoteDiscount','quoteIntegration','quoteData','quoteTraining'].forEach(id=>q(id).addEventListener('input',calcQuote));q('calcQuote').onclick=calcQuote;fillQuoteLeads();calcQuote();renderAll();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();