// Prospectos adicionales con canales comerciales públicos. Actualizado 2026-08-30.
const extraCurated=[
{id:'c30',company:'PIEMAYKA SAC',sector:'Importadora / industrial',district:'Cercado de Lima',phone:'981454216',web:'https://piemaykasac.com.pe/',source:'https://piemaykasac.com.pe/contactanos/',need:'Inventario / POS',score:94,status:'Nuevo',note:'Importadora y comercializadora para minería, pesca, agroindustria, ferretería y construcción. Publica WhatsApp comercial; oportunidad para stock, cotizaciones y pedidos B2B.'},
{id:'c31',company:'SIPFSA',sector:'Importadora / ferretería',district:'Villa El Salvador',phone:'994236232',web:'https://sipfsa.pe/',source:'https://sipfsa.pe/contacto/',need:'Inventario / POS',score:95,status:'Nuevo',note:'Sociedad importadora de productos ferreteros con varias tiendas y WhatsApp de ventas. Muy buen candidato para inventario multisede, cotizaciones y CRM.'},
{id:'c32',company:'Fertisem',sector:'Agroinsumos / veterinaria',district:'Mala - Cañete',phone:'950233689',web:'https://fertisem.pe/',source:'https://fertisem.pe/contactos-fertisem/',need:'Inventario / POS',score:92,status:'Nuevo',note:'Ventas agrícolas y veterinarias por WhatsApp; maneja stock, envíos, facturación y soporte. Oportunidad para pedidos e inventario.'},
{id:'c33',company:'El Pet Shop',sector:'Pet shop / veterinaria',district:'Miraflores',phone:'923517728',web:'https://elpetshop.pe/',source:'https://elpetshop.pe/',need:'Automatización / CRM',score:91,status:'Nuevo',note:'Tienda, veterinaria, baños y pedidos por WhatsApp. Oportunidad para agenda, clientes, inventario y automatización de pedidos.'},
{id:'c34',company:'Family Pets',sector:'Veterinaria / farmacia',district:'Santiago de Surco',phone:'993485130',web:'https://familypets.pe/',source:'https://familypets.pe/',need:'Inventario / POS',score:94,status:'Nuevo',note:'Clínica, farmacia veterinaria, peluquería y atención a domicilio; catálogo amplio y WhatsApp. Potencial para inventario, agenda y CRM.'},
{id:'c35',company:'Veter Perú',sector:'Distribuidora veterinaria',district:'Breña',phone:'959752725',web:'https://veterperu.com.pe/',source:'https://veterperu.com.pe/contacto/',need:'Inventario / POS',score:95,status:'Nuevo',note:'Recibe pedidos directamente por WhatsApp y distribuye productos veterinarios en Lima y provincias. Excelente candidato para stock, pedidos y trazabilidad.'},
{id:'c36',company:'Importaciones Lavsa',sector:'Ferretería / importadora',district:'Santa Anita',phone:'989735756',web:'https://lavsape.com/',source:'https://lavsape.com/',need:'Inventario / POS',score:94,status:'Nuevo',note:'Importadora de ferretería y gasfitería con catálogo amplio, logística y cotizaciones por WhatsApp. Oportunidad para inventario y cotización B2B.'},
{id:'c37',company:'Veterinaria Tilda',sector:'Veterinaria',district:'Ate / Santa Anita',phone:'946351816',web:'https://www.veterinariatilda.com/',source:'https://www.veterinariatilda.com/servicios/laboratorio/',need:'Automatización / CRM',score:91,status:'Nuevo',note:'Tiene sede central y sucursal, agenda por WhatsApp y servicios de laboratorio. Potencial para agenda multisede, historial y recordatorios.'},
{id:'c38',company:'Clínica Veterinaria Dr. Paws',sector:'Veterinaria / pet shop',district:'San Miguel',phone:'999699006',web:'https://www.tiendadrpaws.com/',source:'https://www.tiendadrpaws.com/service-page/laboratorio-cl%C3%ADnico',need:'Automatización / CRM',score:94,status:'Nuevo',note:'Servicios veterinarios y tienda online con WhatsApp separados. Potencial para agenda, CRM, inventario y seguimiento de clientes.'},
{id:'c39',company:'Ferrehogar',sector:'Distribuidora ferretera',district:'San Juan de Miraflores',phone:'901736016',web:'https://ferrehogar.pe/',source:'https://ferrehogar.pe/',need:'Inventario / POS',score:94,status:'Nuevo',note:'Distribuidor ferretero con stock, tienda física, despachos nacionales y asesoría por WhatsApp. Alta oportunidad para stock, ventas y pedidos.'},
{id:'c40',company:'Veterstore / Medixik SAC',sector:'Farmacia veterinaria',district:'San Miguel',phone:'921644174',web:'https://veterstore.com/',source:'https://veterstore.com/',need:'Inventario / POS',score:95,status:'Nuevo',note:'Farmacia veterinaria con cobertura nacional, catálogo e inventario especializado y WhatsApp. Muy buen candidato para stock, pedidos y CRM.'},
{id:'c41',company:'DiagnoPet',sector:'Diagnóstico veterinario',district:'Surquillo',phone:'960390986',web:'https://diagnopet.com.pe/',source:'https://diagnopet.com.pe/contactenos/',need:'Automatización / CRM',score:93,status:'Nuevo',note:'Centro diagnóstico con citas, múltiples tipos de examen y WhatsApp público. Oportunidad para agenda, recordatorios, resultados y CRM.'},
{id:'c42',company:'Ferreterías Callao',sector:'Ferretería',district:'Callao',phone:'923294821',web:'',source:'https://www.google.com/maps/search/?api=1&query=Ferreterias+Callao+Av+Saenz+Pena+793',need:'Inventario / POS',score:90,status:'Nuevo',note:'Ferretería física en Av. Sáenz Peña con teléfono comercial público. Potencial para inventario, POS, catálogo y pedidos.'},
{id:'c43',company:'Importador Seguro',sector:'Importadora',district:'La Victoria',phone:'902430641',web:'',source:'https://www.google.com/maps/search/?api=1&query=Importador+Seguro+Jr+Huanuco+2024+La+Victoria',need:'Sistema a medida',score:91,status:'Nuevo',note:'Empresa importadora con contacto comercial público. Potencial para control de pedidos, cotizaciones, inventario y seguimiento.'},
{id:'c44',company:'Ferreterías Grupo Choque',sector:'Ferretería',district:'Chorrillos',phone:'927131705',web:'',source:'https://www.google.com/maps/search/?api=1&query=Ferreterias+Grupo+Choque+Chorrillos',need:'Inventario / POS',score:89,status:'Nuevo',note:'Tienda física con teléfono comercial público y delivery. Potencial para inventario, POS, catálogo y WhatsApp.'},
{id:'c45',company:'Entre Patas - Urgencias Veterinarias',sector:'Veterinaria',district:'San Martín de Porres',phone:'946857689',web:'',source:'https://www.google.com/maps/search/?api=1&query=Urgencias+Veterinarias+Entre+Patas+San+Martin+de+Porres',need:'Automatización / CRM',score:89,status:'Nuevo',note:'Veterinaria con horario extendido y teléfono público. Oportunidad para agenda, seguimiento, historial y recordatorios.'},
{id:'c46',company:'ServipetSalud',sector:'Veterinaria / farmacia',district:'Cercado de Lima',phone:'937320238',web:'',source:'https://www.google.com/maps/search/?api=1&query=ServipetSalud+Guzman+Blanco+201+Lima',need:'Automatización / CRM',score:91,status:'Nuevo',note:'Urgencias 24h, hospital y farmacia veterinaria con contacto público. Potencial para agenda, pacientes, stock y CRM.'},
{id:'c47',company:'Inversiones Veterinarias San Juan',sector:'Veterinaria / alimentos',district:'Lurín',phone:'967688341',web:'',source:'https://www.google.com/maps/search/?api=1&query=Inversiones+Veterinarias+San+Juan+Lurin',need:'Inventario / POS',score:90,status:'Nuevo',note:'Veterinaria, farmacia y tienda de alimentos con teléfono público. Oportunidad para inventario, ventas y clientes.'}
];
(function mergeExtra(){
 const key=x=>((x.company||'')+'|'+(x.phone||'')).toLowerCase();
 const existing=new Map(leads.map(x=>[key(x),x]));
 extraCurated.forEach(c=>{if(!existing.has(key(c))) leads.push({...c});});
 persist();
 if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',renderCRM); else renderCRM();
})();