(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v||'').replace(/\D/g,'');
function serviceFor(l){const s=(l.service||'').toLowerCase(),sec=(l.sector||'').toLowerCase();if(s)return l.service;if(/ferreter|repuesto|pet shop|óptica|retail|distrib|tienda|tecnolog/.test(sec))return'Inventario / POS';if(/veterin|servicio|taller|salon|clínica/.test(sec))return'CRM / automatización';return l.web?'Automatización / CRM':'Web / catálogo'}
function intelligence(l){const service=serviceFor(l),hasWeb=!!l.web,hasPhone=digits(l.whatsapp||l.phone).length>=9,p=Number(l.priority||70);let signals=[];if(!hasWeb)signals.push('no tiene web registrada');else signals.push('tiene presencia web para revisar');if(hasPhone)signals.push('tiene contacto directo disponible');else signals.push('falta enriquecer un contacto directo');if(/Inventario|POS/i.test(service))signals.push('su rubro maneja stock o rotación');if(/CRM|automat/i.test(service))signals.push('puede tener seguimiento o tareas manuales');if(/Web|catálogo/i.test(service))signals.push('la captación digital puede ser una entrada de bajo costo');const inv=/Inventario|POS/i.test(service),crm=/CRM|automat/i.test(service);const pain=inv?'desorden de stock, conteos manuales o poca visibilidad de productos':crm?'seguimiento manual de clientes, citas, pedidos o tareas repetitivas':'dependencia de redes o WhatsApp sin catálogo propio';const offer=inv?'un control simple de stock/ventas con reportes y alertas':crm?'una automatización pequeña que centralice clientes y seguimiento':'una web/catálogo ligero conectado a WhatsApp';const topic=inv?'el stock y las ventas':crm?'el seguimiento de clientes y tareas':'su catálogo y consultas';const hook='Hola, ¿qué tal? Soy Marcos de MJM Systems. Vi '+(l.company||'su negocio')+' y creo que podríamos ayudarles con '+offer+'. Antes de mandarte una propuesta genérica: ¿hoy cómo manejan '+topic+'?';const why=(l.company||'Este negocio')+' encaja para '+service+' porque '+signals.slice(0,2).join(' y ')+'. La hipótesis a validar es si actualmente tienen '+pain+'.';const questions=inv?['¿Cómo controlan hoy el stock?','¿Cuántas personas actualizan inventario/ventas?','¿Qué problema se repite más: diferencias, búsqueda, reportes o ventas?']:crm?['¿Cómo registran hoy clientes, pedidos o citas?','¿Qué seguimiento hacen manualmente?','¿Qué tarea les quita más tiempo cada semana?']:['¿De dónde llegan más consultas hoy?','¿Tienen catálogo actualizado y fácil de compartir?','¿Qué quisieran que un cliente pueda hacer sin escribirles primero?'];let score=Math.max(1,Math.min(100,Math.round(p+(hasPhone?3:-8)+(!hasWeb&&/Web/.test(service)?5:0))));return{service,offer,hook,why,questions,score,level:score>=90?'Alta':score>=80?'Media-alta':score>=65?'Media':'Por enriquecer'}}
const allLeads=()=>{try{return window.CRM?.DataService?.getLeads?.()||[]}catch{return[]}};
const rank=()=>allLeads().map(l=>({l,i:intelligence(l)})).sort((a,b)=>b.i.score-a.i.score);
function copy(t){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(t);const x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove();return Promise.resolve()}
function ensure(){if(document.getElementById('mjmAiFab'))return;const fab=document.createElement('button');fab.id='mjmAiFab';fab.className='mjmAiFab';fab.innerHTML='<span>✦</span><b>Copiloto</b>';fab.onclick=open;document.body.appendChild(fab);const dlg=document.createElement('dialog');dlg.id='mjmAiDialog';dlg.className='mjmAiDialog';dlg.innerHTML='<div class="mjmAiSheet"><div class="mjmAiTop"><div><small>MJM INTELLIGENCE · V3</small><h2>Copiloto comercial</h2><p>Prioriza prospectos y prepara el siguiente movimiento.</p></div><button id="mjmAiClose">×</button></div><div id="mjmAiBody"></div></div>';document.body.appendChild(dlg);dlg.querySelector('#mjmAiClose').onclick=()=>dlg.close()}
function open(){const dlg=document.getElementById('mjmAiDialog'),body=document.getElementById('mjmAiBody');body.innerHTML='<div class="mjmAiSummary"><b>'+allLeads().length+'</b><span>prospectos analizados</span><em>Modo local · sin API key</em></div><div class="mjmAiSearch"><input id="mjmAiQ" placeholder="Buscar empresa, rubro o zona…"></div><div id="mjmAiList"></div>';const render=(q='')=>{const z=q.toLowerCase().trim();const rows=rank().filter(x=>!z||[x.l.company,x.l.sector,x.l.location,x.i.service].join(' ').toLowerCase().includes(z)).slice(0,20);document.getElementById('mjmAiList').innerHTML=rows.map(({l,i})=>'<article class="mjmAiCard"><div class="mjmAiCardTop"><div><small>'+esc(l.location||'Sin zona')+' · '+esc(l.sector||'Sin rubro')+'</small><h3>'+esc(l.company)+'</h3></div><span>'+i.score+'</span></div><div class="mjmAiTags"><b>'+esc(i.level)+'</b><span>'+esc(i.service)+'</span></div><p>'+esc(i.why)+'</p><div class="mjmAiBox"><small>OFERTA DE ENTRADA</small><b>'+esc(i.offer)+'</b></div><div class="mjmAiBox"><small>3 PREGUNTAS</small><ol>'+i.questions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></div><div class="mjmAiMessage"><small>MENSAJE PERSONALIZADO</small><p>'+esc(i.hook)+'</p><button data-copy="'+encodeURIComponent(i.hook)+'">Copiar mensaje</button></div></article>').join('')||'<p class="mjmAiEmpty">No encontré prospectos con ese filtro.</p>';document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{copy(decodeURIComponent(b.dataset.copy));b.textContent='Copiado ✓';setTimeout(()=>b.textContent='Copiar mensaje',1200)})};render();document.getElementById('mjmAiQ').oninput=e=>render(e.target.value);dlg.showModal()}

function classifyReply(t){const x=String(t||'').toLowerCase();if(!x.trim())return{type:'Vacío',intent:'Pega el mensaje del cliente.',tone:'neutral'};if(/no (me )?interesa|no gracias|no necesito|no queremos/.test(x))return{type:'No interesado',intent:'Cerrar con respeto y conservar la puerta abierta.',tone:'close'};if(/precio|cu[aá]nto|costo|cuesta|tarifa|presupuesto/.test(x))return{type:'Pregunta precio',intent:'Calificar lo mínimo antes de cotizar.',tone:'price'};if(/descuento|rebaja|menos|caro|muy alto/.test(x))return{type:'Objeción de precio',intent:'Defender valor y ajustar alcance antes que regalar margen.',tone:'discount'};if(/ya (tengo|tenemos|uso|usamos).*(sistema|software|excel)|tenemos sistema/.test(x))return{type:'Ya tiene solución',intent:'Descubrir qué sigue siendo manual o deficiente.',tone:'system'};if(/info|informaci[oó]n|detalle|cu[eé]ntame|de qu[eé] trata|qu[eé] incluye/.test(x))return{type:'Pide información',intent:'Explicar breve y hacer una pregunta de descubrimiento.',tone:'info'};if(/demo|muestra|verlo|ejemplo/.test(x))return{type:'Quiere demo',intent:'Convertir curiosidad en una demo enfocada a su problema.',tone:'demo'};if(/interesa|podemos hablar|conversemos|me sirve|quiero/.test(x))return{type:'Interesado',intent:'Pasar del interés a datos concretos y siguiente acción.',tone:'interested'};if(/despu[eé]s|otro d[ií]a|m[aá]s adelante|ahora no|ocupad/.test(x))return{type:'Posponer',intent:'Pactar un seguimiento concreto sin presionar.',tone:'later'};return{type:'Respuesta abierta',intent:'Entender qué necesita antes de vender.',tone:'open'}}
function replyFor(l,t){const k=classifyReply(t),i=intelligence(l||{}),name=l?.company||'tu negocio';let reply,next;
if(k.tone==='price'){reply='Sí, te puedo dar un precio. Para no inventarte una cifra, dime solo dos cosas: qué parte necesitas resolver primero y cuántas personas o sedes lo usarían. Con eso te doy una opción aterrizada.';next='Recoger alcance mínimo y preparar rango/precio.'}
else if(k.tone==='discount'){reply='Podemos cuidar el presupuesto ajustando el alcance. Prefiero quitar funciones que no sean urgentes antes que entregarte algo incompleto. ¿Qué sería indispensable que funcione desde el primer día?';next='Definir MVP y recién después ajustar precio.'}
else if(k.tone==='system'){reply='Buenísimo, si ya tienen algo que funciona no tendría sentido cambiarlo por cambiarlo. ¿Qué parte todavía hacen manualmente o qué les gustaría que su sistema actual resolviera mejor?';next='Encontrar una brecha concreta del sistema actual.'}
else if(k.tone==='info'){reply='Claro. En MJM Systems hacemos soluciones pequeñas y a medida para ordenar procesos y ahorrar trabajo manual. En el caso de '+name+', la idea que veo es '+i.offer+'. Para orientarte bien, ¿cómo manejan eso actualmente?';next='Descubrir proceso actual y dolor principal.'}
else if(k.tone==='demo'){reply='Sí, te puedo mostrar una demo, pero prefiero enseñarte algo que se parezca a tu caso y no una pantalla genérica. ¿Qué te gustaría ver funcionando primero?';next='Definir caso de uso y preparar demo enfocada.'}
else if(k.tone==='interested'){reply='Buenísimo. Para aterrizarlo rápido, cuéntame dos cosas: ¿qué problema quieres resolver primero y cómo lo manejas hoy? Con eso te propongo el camino más simple.';next='Calificar necesidad y llevar a propuesta/demo.'}
else if(k.tone==='later'){reply='Claro, ningún problema. Para no insistirte fuera de momento, ¿te parece si lo retomamos más adelante? Si quieres, antes te dejo en una línea la idea que tenía para '+name+'.';next='Acordar fecha de seguimiento.'}
else if(k.tone==='close'){reply='Entendido, gracias por responder. No te quito más tiempo. Si más adelante necesitan ordenar algún proceso, inventario, ventas o automatizar tareas, quedo a disposición.';next='Cerrar contacto y no insistir.'}
else{reply='Gracias por responder. Para no asumir cosas: ¿qué parte de ese proceso te gustaría mejorar o qué es lo que más tiempo te quita actualmente?';next='Hacer una pregunta abierta y detectar dolor.'}
return{...k,reply,next,service:i.service}}
function openReplyAssistant(){ensure();const dlg=document.getElementById('mjmAiDialog'),body=document.getElementById('mjmAiBody'),leads=allLeads().slice().sort((a,b)=>String(a.company).localeCompare(String(b.company)));body.innerHTML='<div class="mjmAiReplyHead"><b>Asistente de respuestas</b><span>Pega exactamente lo que respondió el prospecto.</span></div><label class="mjmAiLabel">Prospecto<select id="mjmReplyLead">'+leads.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.company)+'</option>').join('')+'</select></label><label class="mjmAiLabel">Mensaje recibido<textarea id="mjmReplyText" rows="5" placeholder="Ej.: ¿Cuánto cuesta? / Ya tenemos sistema / Mándame información…"></textarea></label><button class="mjmAiAnalyze" id="mjmReplyAnalyze">Analizar respuesta</button><div id="mjmReplyResult"></div>';document.getElementById('mjmReplyAnalyze').onclick=()=>{const l=leads.find(x=>x.id===document.getElementById('mjmReplyLead').value)||leads[0],r=replyFor(l,document.getElementById('mjmReplyText').value),out=document.getElementById('mjmReplyResult');out.innerHTML='<div class="mjmAiResult"><div class="mjmAiTags"><b>'+esc(r.type)+'</b><span>'+esc(r.service)+'</span></div><small>OBJETIVO</small><p>'+esc(r.intent)+'</p><small>RESPUESTA SUGERIDA</small><div class="mjmAiSuggested">'+esc(r.reply)+'</div><button id="mjmCopyReply">Copiar respuesta</button><small>SIGUIENTE PASO</small><p><b>'+esc(r.next)+'</b></p></div>';document.getElementById('mjmCopyReply').onclick=e=>{copy(r.reply);e.currentTarget.textContent='Copiado ✓'}};dlg.showModal()}
function boot(){ensure();window.MJMAI={intelligence,rank,open,classifyReply,replyFor,openReplyAssistant};const fab=document.getElementById('mjmAiFab');if(fab){fab.onclick=()=>{const dlg=document.getElementById('mjmAiDialog'),body=document.getElementById('mjmAiBody');body.innerHTML='<div class="mjmAiMenu"><button id="mjmOpenIntel"><b>✦ Inteligencia de leads</b><span>Prioridad, oferta, preguntas y primer mensaje.</span></button><button id="mjmOpenReply"><b>💬 Asistente de respuestas</b><span>Pega lo que dijo el prospecto y prepara tu respuesta.</span></button></div>';document.getElementById('mjmOpenIntel').onclick=open;document.getElementById('mjmOpenReply').onclick=openReplyAssistant;dlg.showModal()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300));else setTimeout(boot,300);
})();