(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v||'').replace(/\D/g,'');
function serviceFor(l){const s=(l.service||'').toLowerCase(),sec=(l.sector||'').toLowerCase();if(s)return l.service;if(/ferreter|repuesto|pet shop|óptica|retail|distrib|tienda|tecnolog/.test(sec))return'Inventario / POS';if(/veterin|servicio|taller|salon|clínica/.test(sec))return'CRM / automatización';return l.web?'Automatización / CRM':'Web / catálogo'}
function intelligence(l){const service=serviceFor(l),hasWeb=!!l.web,hasPhone=digits(l.whatsapp||l.phone).length>=9,p=Number(l.priority||70);let signals=[];if(!hasWeb)signals.push('no tiene web registrada');else signals.push('tiene presencia web para revisar');if(hasPhone)signals.push('tiene contacto directo disponible');else signals.push('falta enriquecer un contacto directo');if(/Inventario|POS/i.test(service))signals.push('su rubro maneja stock o rotación');if(/CRM|automat/i.test(service))signals.push('puede tener seguimiento o tareas manuales');if(/Web|catálogo/i.test(service))signals.push('la captación digital puede ser una entrada de bajo costo');const inv=/Inventario|POS/i.test(service),crm=/CRM|automat/i.test(service);const pain=inv?'desorden de stock, conteos manuales o poca visibilidad de productos':crm?'seguimiento manual de clientes, citas, pedidos o tareas repetitivas':'dependencia de redes o WhatsApp sin catálogo propio';const offer=inv?'un control simple de stock/ventas con reportes y alertas':crm?'una automatización pequeña que centralice clientes y seguimiento':'una web/catálogo ligero conectado a WhatsApp';const topic=inv?'el stock y las ventas':crm?'el seguimiento de clientes y tareas':'su catálogo y consultas';const hook='Hola, ¿qué tal? Soy Marcos de MJM Systems. Vi '+(l.company||'su negocio')+' y creo que podríamos ayudarles con '+offer+'. Antes de mandarte una propuesta genérica: ¿hoy cómo manejan '+topic+'?';const why=(l.company||'Este negocio')+' encaja para '+service+' porque '+signals.slice(0,2).join(' y ')+'. La hipótesis a validar es si actualmente tienen '+pain+'.';const questions=inv?['¿Cómo controlan hoy el stock?','¿Cuántas personas actualizan inventario/ventas?','¿Qué problema se repite más: diferencias, búsqueda, reportes o ventas?']:crm?['¿Cómo registran hoy clientes, pedidos o citas?','¿Qué seguimiento hacen manualmente?','¿Qué tarea les quita más tiempo cada semana?']:['¿De dónde llegan más consultas hoy?','¿Tienen catálogo actualizado y fácil de compartir?','¿Qué quisieran que un cliente pueda hacer sin escribirles primero?'];let score=Math.max(1,Math.min(100,Math.round(p+(hasPhone?3:-8)+(!hasWeb&&/Web/.test(service)?5:0))));return{service,offer,hook,why,questions,score,level:score>=90?'Alta':score>=80?'Media-alta':score>=65?'Media':'Por enriquecer'}}
const allLeads=()=>{try{return window.CRM?.DataService?.getLeads?.()||[]}catch{return[]}};
const rank=()=>allLeads().map(l=>({l,i:intelligence(l)})).sort((a,b)=>b.i.score-a.i.score);
function copy(t){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(t);const x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove();return Promise.resolve()}
function ensure(){if(document.getElementById('mjmAiFab'))return;const fab=document.createElement('button');fab.id='mjmAiFab';fab.className='mjmAiFab';fab.innerHTML='<span>✦</span><b>Copiloto</b>';fab.onclick=open;document.body.appendChild(fab);const dlg=document.createElement('dialog');dlg.id='mjmAiDialog';dlg.className='mjmAiDialog';dlg.innerHTML='<div class="mjmAiSheet"><div class="mjmAiTop"><div><small>MJM INTELLIGENCE · V3</small><h2>Copiloto comercial</h2><p>Prioriza prospectos y prepara el siguiente movimiento.</p></div><button id="mjmAiClose">×</button></div><div id="mjmAiBody"></div></div>';document.body.appendChild(dlg);dlg.querySelector('#mjmAiClose').onclick=()=>dlg.close()}
function open(){const dlg=document.getElementById('mjmAiDialog'),body=document.getElementById('mjmAiBody');body.innerHTML='<div class="mjmAiSummary"><b>'+allLeads().length+'</b><span>prospectos analizados</span><em>Modo local · sin API key</em></div><div class="mjmAiSearch"><input id="mjmAiQ" placeholder="Buscar empresa, rubro o zona…"></div><div id="mjmAiList"></div>';const render=(q='')=>{const z=q.toLowerCase().trim();const rows=rank().filter(x=>!z||[x.l.company,x.l.sector,x.l.location,x.i.service].join(' ').toLowerCase().includes(z)).slice(0,20);document.getElementById('mjmAiList').innerHTML=rows.map(({l,i})=>'<article class="mjmAiCard"><div class="mjmAiCardTop"><div><small>'+esc(l.location||'Sin zona')+' · '+esc(l.sector||'Sin rubro')+'</small><h3>'+esc(l.company)+'</h3></div><span>'+i.score+'</span></div><div class="mjmAiTags"><b>'+esc(i.level)+'</b><span>'+esc(i.service)+'</span></div><p>'+esc(i.why)+'</p><div class="mjmAiBox"><small>OFERTA DE ENTRADA</small><b>'+esc(i.offer)+'</b></div><div class="mjmAiBox"><small>3 PREGUNTAS</small><ol>'+i.questions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></div><div class="mjmAiMessage"><small>MENSAJE PERSONALIZADO</small><p>'+esc(i.hook)+'</p><button data-copy="'+encodeURIComponent(i.hook)+'">Copiar mensaje</button></div></article>').join('')||'<p class="mjmAiEmpty">No encontré prospectos con ese filtro.</p>';document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{copy(decodeURIComponent(b.dataset.copy));b.textContent='Copiado ✓';setTimeout(()=>b.textContent='Copiar mensaje',1200)})};render();document.getElementById('mjmAiQ').oninput=e=>render(e.target.value);dlg.showModal()}
function boot(){ensure();window.MJMAI={intelligence,rank,open}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300));else setTimeout(boot,300);
})();